import "server-only";

import crypto from "node:crypto";
import { getDocuSignSession } from "./auth";
import { getEmbeddedSigningOrigins } from "./config";
import { DocuSignApiError } from "./errors";

function parseJsonText(text) {
  if (!text) {
    return null;
  }

  try {
    return JSON.parse(text);
  } catch {
    return { raw: text };
  }
}

function buildDemoAgreementHtml({ agreementTitle, signerName }) {
  return `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${agreementTitle}</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        color: #161616;
        margin: 48px;
        line-height: 1.6;
      }

      h1 {
        margin-bottom: 8px;
      }

      .meta {
        color: #666;
        margin-bottom: 32px;
      }

      .signature-grid {
        margin-top: 56px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 24px;
      }

      .signature-box {
        border-top: 1px solid #1f1f1f;
        padding-top: 12px;
        min-height: 72px;
      }
    </style>
  </head>
  <body>
    <h1>${agreementTitle}</h1>
    <p class="meta">Prepared for ${signerName} through the Far Flung Change signing flow.</p>
    <p>
      This is a starter agreement generated by the application so you can prove out the embedded
      signing flow end to end without leaving the site.
    </p>
    <p>
      Replace this HTML document with a template, generated PDF, or stored agreement once you are
      ready to connect your real business workflow.
    </p>

    <section class="signature-grid">
      <div class="signature-box">
        <strong>Signer</strong><br />
        /sn1/
      </div>
      <div class="signature-box">
        <strong>Date Signed</strong><br />
        /ds1/
      </div>
    </section>
  </body>
</html>
  `.trim();
}

async function postToDocuSign(session, pathname, body) {
  const response = await fetch(`${session.basePath}${pathname}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${session.accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
    cache: "no-store",
  });
  const text = await response.text();
  const data = parseJsonText(text);

  if (!response.ok) {
    throw new DocuSignApiError(data?.message || "A DocuSign API call failed.", {
      status: response.status,
      details: data,
    });
  }

  return data;
}

async function createEnvelope({
  signerName,
  signerEmail,
  agreementTitle,
  clientUserId,
}) {
  const session = await getDocuSignSession();
  const htmlDocument = buildDemoAgreementHtml({
    agreementTitle,
    signerName,
  });
  const envelopeDefinition = {
    emailSubject: agreementTitle,
    documents: [
      {
        documentBase64: Buffer.from(htmlDocument).toString("base64"),
        name: `${agreementTitle}.html`,
        fileExtension: "html",
        documentId: "1",
      },
    ],
    recipients: {
      signers: [
        {
          email: signerEmail,
          name: signerName,
          recipientId: "1",
          routingOrder: "1",
          clientUserId,
          tabs: {
            signHereTabs: [
              {
                anchorString: "/sn1/",
                anchorUnits: "pixels",
                anchorXOffset: "20",
                anchorYOffset: "-12",
              },
            ],
            dateSignedTabs: [
              {
                anchorString: "/ds1/",
                anchorUnits: "pixels",
                anchorXOffset: "0",
                anchorYOffset: "-12",
              },
            ],
          },
        },
      ],
    },
    status: "sent",
  };

  const data = await postToDocuSign(
    session,
    `/v2.1/accounts/${encodeURIComponent(session.accountId)}/envelopes`,
    envelopeDefinition
  );

  return {
    session,
    envelopeId: data?.envelopeId || data?.envelope_id,
  };
}

async function createRecipientView({
  session,
  envelopeId,
  signerName,
  signerEmail,
  clientUserId,
  returnUrl,
  requestOrigin,
}) {
  const { frameAncestors, messageOrigins } = getEmbeddedSigningOrigins(requestOrigin);
  const recipientViewRequest = {
    returnUrl,
    authenticationMethod: "none",
    email: signerEmail,
    userName: signerName,
    clientUserId,
    frameAncestors,
    messageOrigins,
  };
  const data = await postToDocuSign(
    session,
    `/v2.1/accounts/${encodeURIComponent(session.accountId)}/envelopes/${encodeURIComponent(envelopeId)}/views/recipient`,
    recipientViewRequest
  );

  return data?.url;
}

export async function createEmbeddedSigningSession({
  signerName,
  signerEmail,
  agreementTitle,
  requestOrigin,
  returnUrl,
}) {
  const normalizedName = signerName.trim();
  const normalizedEmail = signerEmail.trim().toLowerCase();
  const normalizedTitle = agreementTitle.trim();
  const clientUserId = crypto.randomUUID();

  const { session, envelopeId } = await createEnvelope({
    signerName: normalizedName,
    signerEmail: normalizedEmail,
    agreementTitle: normalizedTitle,
    clientUserId,
  });

  if (!envelopeId) {
    throw new DocuSignApiError("DocuSign did not return an envelope ID.", {
      status: 502,
    });
  }

  const recipientViewUrl = await createRecipientView({
    session,
    envelopeId,
    signerName: normalizedName,
    signerEmail: normalizedEmail,
    clientUserId,
    returnUrl,
    requestOrigin,
  });

  if (!recipientViewUrl) {
    throw new DocuSignApiError("DocuSign did not return a recipient view URL.", {
      status: 502,
    });
  }

  return {
    envelopeId,
    recipientViewUrl,
    docuSignSession: {
      accountId: session.accountId,
      basePath: session.basePath,
    },
  };
}
